# syntax = docker/dockerfile:1

# Ever Teams Platform

ARG NODE_VERSION=22.18.0
ARG NEXT_IGNORE_ESLINT_ERROR_ON_BUILD=true
ARG RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED=false
ARG IS_DESKTOP_APP=false

ARG NEXT_PUBLIC_GAUZY_API_SERVER_URL
ARG NEXT_PUBLIC_GA_MEASUREMENT_ID
ARG NEXT_PUBLIC_CAPTCHA_SITE_KEY
ARG NEXT_PUBLIC_DISABLE_AUTO_REFRESH
ARG NEXT_PUBLIC_COOKIE_DOMAINS
ARG NEXT_PUBLIC_BOARD_APP_DOMAIN
ARG NEXT_PUBLIC_BOARD_BACKEND_POST_URL
ARG NEXT_PUBLIC_BOARD_FIREBASE_CONFIG
ARG NEXT_PUBLIC_MEET_DOMAIN
ARG NEXT_PUBLIC_SENTRY_DSN
ARG NEXT_PUBLIC_SENTRY_DEBUG
ARG NEXT_PUBLIC_JITSU_BROWSER_URL
ARG NEXT_PUBLIC_JITSU_BROWSER_WRITE_KEY
ARG NEXT_PUBLIC_GITHUB_APP_NAME
ARG NEXT_PUBLIC_CHATWOOT_API_KEY

# App Branding Variables
ARG APP_NAME
ARG APP_SIGNATURE
ARG APP_LOGO_URL
ARG APP_LINK
ARG APP_SLOGAN_TEXT
ARG COMPANY_NAME
ARG COMPANY_LINK
ARG TERMS_LINK
ARG PRIVACY_POLICY_LINK
ARG MAIN_PICTURE
ARG MAIN_PICTURE_DARK

# Site Metadata Variables
ARG NEXT_PUBLIC_SITE_NAME
ARG NEXT_PUBLIC_SITE_TITLE
ARG NEXT_PUBLIC_SITE_DESCRIPTION
ARG NEXT_PUBLIC_SITE_KEYWORDS
ARG NEXT_PUBLIC_WEB_APP_URL
ARG NEXT_PUBLIC_TWITTER_USERNAME
ARG NEXT_PUBLIC_IMAGES_HOSTS

# OAuth Configuration
ARG NEXT_PUBLIC_GOOGLE_APP_NAME
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG NEXT_PUBLIC_FACEBOOK_APP_NAME
ARG FACEBOOK_CLIENT_ID
ARG FACEBOOK_CLIENT_SECRET
ARG NEXT_PUBLIC_TWITTER_APP_NAME
ARG TWITTER_CLIENT_ID
ARG TWITTER_CLIENT_SECRET
ARG GITHUB_CLIENT_ID
ARG GITHUB_CLIENT_SECRET

# Additional Configuration
ARG NEXT_PUBLIC_CAPTCHA_TYPE
ARG NEXT_PUBLIC_MEET_TYPE
ARG LIVEKIT_API_SECRET
ARG LIVEKIT_API_KEY
ARG NEXT_PUBLIC_LIVEKIT_URL
ARG INVITE_CALLBACK_URL
ARG VERIFY_EMAIL_CALLBACK_URL
ARG SMTP_PORT
ARG SENTRY_LOG_LEVEL
ARG NEXT_PUBLIC_POSTHOG_KEY
ARG NEXT_PUBLIC_POSTHOG_HOST
ARG LOG_FOLDER_MAX_SIZE
ARG NEXT_PUBLIC_LOG_FOLDER_MAX_SIZE
ARG ACTIVE_LOCAL_LOG_SYSTEM
ARG NEXT_PUBLIC_ACTIVE_LOCAL_LOG_SYSTEM
ARG NEXT_PUBLIC_DEMO=false
ARG ANALYZE

# Server Configuration
ARG GAUZY_API_SERVER_URL
ARG JITSU_SERVER_URL
ARG JITSU_SERVER_WRITE_KEY
ARG AUTH_SECRET
ARG CAPTCHA_SECRET_KEY
ARG SMTP_FROM_ADDRESS
ARG SMTP_HOST
ARG SMTP_SECURE=true
ARG SMTP_USERNAME
ARG SMTP_PASSWORD
ARG MEET_JWT_APP_ID
ARG MEET_JWT_APP_SECRET
ARG SENTRY_ORG
ARG SENTRY_PROJECT
ARG SENTRY_AUTH_TOKEN
ARG SENTRY_DSN
ARG POSTMARK_SERVER_API_TOKEN
ARG MAILCHIMP_API_KEY
ARG MAILCHIMP_LIST_ID

FROM node:${NODE_VERSION}-slim AS base

LABEL maintainer='ever@ever.co'
LABEL org.opencontainers.image.source='https://github.com/ever-co/ever-teams'

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_BUILD_OUTPUT_TYPE=standalone
ENV NEXT_SHARP_PATH=/temp/node_modules/sharp

RUN npm i -g npm@9

# Pre-install Sharp for Next.js image optimization support
RUN mkdir /temp && cd /temp && npm i sharp

RUN npm cache clean --force

# Throw-away build stage to reduce size of final image
FROM base AS build

# Install packages needed to build node modules
RUN apt-get update -qq && \
	apt-get install -y build-essential pkg-config python-is-python3

# Install Yarn
RUN npm install -g yarn --force

# --- STEP 1: Copy only lockfiles and manifests for dependency resolution ---
COPY package.json yarn.lock ./

COPY packages/constants/package.json packages/constants/package.json
COPY packages/types/package.json packages/types/package.json
COPY packages/utils/package.json packages/utils/package.json
COPY packages/ui/package.json packages/ui/package.json
COPY packages/services/package.json packages/services/package.json
COPY packages/hooks/package.json packages/hooks/package.json
COPY packages/eslint-config/package.json packages/eslint-config/package.json
COPY packages/ts-config/package.json packages/ts-config/package.json
COPY apps/web/package.json ./apps/web/package.json

# Set working directory to the web app
WORKDIR /app/apps/web

# --- STEP 2: Install deps in deterministic and cacheable way ---
RUN yarn install --frozen-lockfile --non-interactive --ignore-scripts

# --- STEP 3: Copy the rest of the repo for build ---
WORKDIR /app
COPY . .

ENV CI=true

# We make NODE_ENV and other env vars passed as build argument to be available in this stage
ARG NODE_ENV
ARG NEXT_PUBLIC_DEMO
ARG ANALYZE
ARG NODE_OPTIONS

ARG NEXT_PUBLIC_GAUZY_API_SERVER_URL
ARG NEXT_PUBLIC_GA_MEASUREMENT_ID
ARG NEXT_PUBLIC_CAPTCHA_SITE_KEY
ARG NEXT_PUBLIC_DISABLE_AUTO_REFRESH
ARG NEXT_PUBLIC_COOKIE_DOMAINS
ARG NEXT_PUBLIC_BOARD_APP_DOMAIN
ARG NEXT_PUBLIC_BOARD_BACKEND_POST_URL
ARG NEXT_PUBLIC_BOARD_FIREBASE_CONFIG
ARG NEXT_PUBLIC_MEET_DOMAIN
ARG NEXT_PUBLIC_SENTRY_DSN
ARG NEXT_PUBLIC_SENTRY_DEBUG
ARG NEXT_PUBLIC_JITSU_BROWSER_URL
ARG NEXT_PUBLIC_JITSU_BROWSER_WRITE_KEY
ARG NEXT_PUBLIC_GITHUB_APP_NAME
ARG NEXT_PUBLIC_CHATWOOT_API_KEY

# App Branding Variables
ARG APP_NAME
ARG APP_SIGNATURE
ARG APP_LOGO_URL
ARG APP_LINK
ARG APP_SLOGAN_TEXT
ARG COMPANY_NAME
ARG COMPANY_LINK
ARG TERMS_LINK
ARG PRIVACY_POLICY_LINK
ARG MAIN_PICTURE
ARG MAIN_PICTURE_DARK

# Site Metadata Variables
ARG NEXT_PUBLIC_SITE_NAME
ARG NEXT_PUBLIC_SITE_TITLE
ARG NEXT_PUBLIC_SITE_DESCRIPTION
ARG NEXT_PUBLIC_SITE_KEYWORDS
ARG NEXT_PUBLIC_WEB_APP_URL
ARG NEXT_PUBLIC_TWITTER_USERNAME
ARG NEXT_PUBLIC_IMAGES_HOSTS

# OAuth Configuration
ARG NEXT_PUBLIC_GOOGLE_APP_NAME
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG NEXT_PUBLIC_FACEBOOK_APP_NAME
ARG FACEBOOK_CLIENT_ID
ARG FACEBOOK_CLIENT_SECRET
ARG NEXT_PUBLIC_TWITTER_APP_NAME
ARG TWITTER_CLIENT_ID
ARG TWITTER_CLIENT_SECRET
ARG GITHUB_CLIENT_ID
ARG GITHUB_CLIENT_SECRET

# Additional Configuration
ARG NEXT_PUBLIC_CAPTCHA_TYPE
ARG NEXT_PUBLIC_MEET_TYPE
ARG LIVEKIT_API_SECRET
ARG LIVEKIT_API_KEY
ARG NEXT_PUBLIC_LIVEKIT_URL
ARG INVITE_CALLBACK_URL
ARG VERIFY_EMAIL_CALLBACK_URL
ARG SMTP_PORT
ARG SENTRY_LOG_LEVEL
ARG NEXT_PUBLIC_POSTHOG_KEY
ARG NEXT_PUBLIC_POSTHOG_HOST
ARG LOG_FOLDER_MAX_SIZE
ARG NEXT_PUBLIC_LOG_FOLDER_MAX_SIZE
ARG ACTIVE_LOCAL_LOG_SYSTEM
ARG NEXT_PUBLIC_ACTIVE_LOCAL_LOG_SYSTEM
ARG NEXT_PUBLIC_DEMO
ARG ANALYZE

# Server Configuration
ARG GAUZY_API_SERVER_URL
ARG JITSU_SERVER_URL
ARG JITSU_SERVER_WRITE_KEY
ARG AUTH_SECRET
ARG CAPTCHA_SECRET_KEY
ARG SMTP_FROM_ADDRESS
ARG SMTP_HOST
ARG SMTP_SECURE=true
ARG SMTP_USERNAME
ARG SMTP_PASSWORD
ARG MEET_JWT_APP_ID
ARG MEET_JWT_APP_SECRET
ARG SENTRY_ORG
ARG SENTRY_PROJECT
ARG SENTRY_AUTH_TOKEN
ARG SENTRY_DSN
ARG POSTMARK_SERVER_API_TOKEN
ARG MAILCHIMP_API_KEY
ARG MAILCHIMP_LIST_ID

ENV NODE_OPTIONS=${NODE_OPTIONS:-"--max-old-space-size=60000"}
ENV NODE_ENV=${NODE_ENV:-production}
ENV NEXT_IGNORE_ESLINT_ERROR_ON_BUILD=true
ENV NEXT_PUBLIC_DEMO=${NEXT_PUBLIC_DEMO:-false}
ENV IS_DESKTOP_APP=false
ENV ANALYZE=${ANALYZE:-false}

ENV IS_DOCKER=true

ENV NEXT_PUBLIC_GAUZY_API_SERVER_URL=${NEXT_PUBLIC_GAUZY_API_SERVER_URL}
ENV NEXT_PUBLIC_GA_MEASUREMENT_ID=${NEXT_PUBLIC_GA_MEASUREMENT_ID}
ENV NEXT_PUBLIC_CAPTCHA_SITE_KEY=${NEXT_PUBLIC_CAPTCHA_SITE_KEY}
ENV NEXT_PUBLIC_DISABLE_AUTO_REFRESH=${NEXT_PUBLIC_DISABLE_AUTO_REFRESH:-false}
ENV NEXT_PUBLIC_COOKIE_DOMAINS=${NEXT_PUBLIC_COOKIE_DOMAINS}
ENV NEXT_PUBLIC_BOARD_APP_DOMAIN=${NEXT_PUBLIC_BOARD_APP_DOMAIN}
ENV NEXT_PUBLIC_BOARD_BACKEND_POST_URL=${NEXT_PUBLIC_BOARD_BACKEND_POST_URL}
ENV NEXT_PUBLIC_BOARD_FIREBASE_CONFIG=${NEXT_PUBLIC_BOARD_FIREBASE_CONFIG}
ENV NEXT_PUBLIC_MEET_DOMAIN=${NEXT_PUBLIC_MEET_DOMAIN}
ENV NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN}
ENV NEXT_PUBLIC_SENTRY_DEBUG=${NEXT_PUBLIC_SENTRY_DEBUG}
ENV NEXT_PUBLIC_JITSU_BROWSER_URL=${NEXT_PUBLIC_JITSU_BROWSER_URL}
ENV NEXT_PUBLIC_JITSU_BROWSER_WRITE_KEY=${NEXT_PUBLIC_JITSU_BROWSER_WRITE_KEY}
ENV NEXT_PUBLIC_GITHUB_APP_NAME=${NEXT_PUBLIC_GITHUB_APP_NAME}
ENV NEXT_PUBLIC_CHATWOOT_API_KEY=${NEXT_PUBLIC_CHATWOOT_API_KEY}

# App Branding Variables
ENV APP_NAME=${APP_NAME}
ENV APP_SIGNATURE=${APP_SIGNATURE}
ENV APP_LOGO_URL=${APP_LOGO_URL}
ENV APP_LINK=${APP_LINK}
ENV APP_SLOGAN_TEXT=${APP_SLOGAN_TEXT}
ENV COMPANY_NAME=${COMPANY_NAME}
ENV COMPANY_LINK=${COMPANY_LINK}
ENV TERMS_LINK=${TERMS_LINK}
ENV PRIVACY_POLICY_LINK=${PRIVACY_POLICY_LINK}
ENV MAIN_PICTURE=${MAIN_PICTURE}
ENV MAIN_PICTURE_DARK=${MAIN_PICTURE_DARK}

# Site Metadata Variables
ENV NEXT_PUBLIC_SITE_NAME=${NEXT_PUBLIC_SITE_NAME}
ENV NEXT_PUBLIC_SITE_TITLE=${NEXT_PUBLIC_SITE_TITLE}
ENV NEXT_PUBLIC_SITE_DESCRIPTION=${NEXT_PUBLIC_SITE_DESCRIPTION}
ENV NEXT_PUBLIC_SITE_KEYWORDS=${NEXT_PUBLIC_SITE_KEYWORDS}
ENV NEXT_PUBLIC_WEB_APP_URL=${NEXT_PUBLIC_WEB_APP_URL}
ENV NEXT_PUBLIC_TWITTER_USERNAME=${NEXT_PUBLIC_TWITTER_USERNAME}
ENV NEXT_PUBLIC_IMAGES_HOSTS=${NEXT_PUBLIC_IMAGES_HOSTS}

# OAuth Configuration
ENV NEXT_PUBLIC_GOOGLE_APP_NAME=${NEXT_PUBLIC_GOOGLE_APP_NAME}
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV NEXT_PUBLIC_FACEBOOK_APP_NAME=${NEXT_PUBLIC_FACEBOOK_APP_NAME}
ENV FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
ENV FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
ENV NEXT_PUBLIC_TWITTER_APP_NAME=${NEXT_PUBLIC_TWITTER_APP_NAME}
ENV TWITTER_CLIENT_ID=${TWITTER_CLIENT_ID}
ENV TWITTER_CLIENT_SECRET=${TWITTER_CLIENT_SECRET}
ENV GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
ENV GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}

# Additional Configuration
ENV NEXT_PUBLIC_CAPTCHA_TYPE=${NEXT_PUBLIC_CAPTCHA_TYPE}
ENV NEXT_PUBLIC_MEET_TYPE=${NEXT_PUBLIC_MEET_TYPE}
ENV LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
ENV LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
ENV NEXT_PUBLIC_LIVEKIT_URL=${NEXT_PUBLIC_LIVEKIT_URL}
ENV INVITE_CALLBACK_URL=${INVITE_CALLBACK_URL}
ENV VERIFY_EMAIL_CALLBACK_URL=${VERIFY_EMAIL_CALLBACK_URL}
ENV SENTRY_LOG_LEVEL=${SENTRY_LOG_LEVEL:-error}
ENV NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
ENV NEXT_PUBLIC_POSTHOG_HOST=${NEXT_PUBLIC_POSTHOG_HOST}
ENV LOG_FOLDER_MAX_SIZE=${LOG_FOLDER_MAX_SIZE:-10}
ENV NEXT_PUBLIC_LOG_FOLDER_MAX_SIZE=${NEXT_PUBLIC_LOG_FOLDER_MAX_SIZE:-10}
ENV ACTIVE_LOCAL_LOG_SYSTEM=${ACTIVE_LOCAL_LOG_SYSTEM:-false}
ENV NEXT_PUBLIC_ACTIVE_LOCAL_LOG_SYSTEM=${NEXT_PUBLIC_ACTIVE_LOCAL_LOG_SYSTEM:-false}

# Server Configuration
ENV GAUZY_API_SERVER_URL=${GAUZY_API_SERVER_URL}
ENV JITSU_SERVER_URL=${JITSU_SERVER_URL}
ENV JITSU_SERVER_WRITE_KEY=${JITSU_SERVER_WRITE_KEY}
ENV AUTH_SECRET=${AUTH_SECRET}
ENV CAPTCHA_SECRET_KEY=${CAPTCHA_SECRET_KEY}
ENV SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}
ENV SMTP_HOST=${SMTP_HOST}
ENV SMTP_PORT=${SMTP_PORT:-587}
ENV SMTP_SECURE=${SMTP_SECURE:-true}
ENV SMTP_USERNAME=${SMTP_USERNAME}
ENV SMTP_PASSWORD=${SMTP_PASSWORD}
ENV MEET_JWT_APP_ID=${MEET_JWT_APP_ID}
ENV MEET_JWT_APP_SECRET=${MEET_JWT_APP_SECRET}
ENV SENTRY_ORG=${SENTRY_ORG}
ENV SENTRY_PROJECT=${SENTRY_PROJECT}
ENV SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
ENV SENTRY_DSN=${SENTRY_DSN}
ENV NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN}
ENV POSTMARK_SERVER_API_TOKEN=${POSTMARK_SERVER_API_TOKEN}
ENV MAILCHIMP_API_KEY=${MAILCHIMP_API_KEY}
ENV MAILCHIMP_LIST_ID=${MAILCHIMP_LIST_ID}

# --- STEP 4: Build the web application ---
RUN yarn run build:web

# --- STEP 5: Remove dev dependencies and clean cache --- Remove dev dependencies (to reduce final image size)
WORKDIR /app/apps/web
RUN yarn install --prod --ignore-scripts
RUN yarn cache clean

# ------------------------------------------------------------------------------
# Runtime stage: lightweight image that serves the built application
# ------------------------------------------------------------------------------

FROM base

# Copy build artifacts from the previous stage
COPY --from=build /app/apps/web/.next/standalone ./
COPY --from=build /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=build /app/apps/web/public ./apps/web/public

# We make NODE_ENV and other env vars passed as build argument to be available in this stage
ARG NODE_ENV
ARG NEXT_PUBLIC_DEMO
ARG ANALYZE
ARG NODE_OPTIONS

ENV HOSTNAME=0.0.0.0
ENV NODE_OPTIONS=${NODE_OPTIONS:-"--max-old-space-size=12288"}
ENV NODE_ENV=${NODE_ENV:-production}
ENV NEXT_IGNORE_ESLINT_ERROR_ON_BUILD=true
ENV NEXT_PUBLIC_DEMO=${NEXT_PUBLIC_DEMO:-false}
ENV IS_DESKTOP_APP=false
ENV ANALYZE=${ANALYZE:-false}

ENV IS_DOCKER=true

# Default port for the web server
EXPOSE 3030
ENV PORT=3030

# Start Next.js server
CMD ["node", "./apps/web/server.js"]
