export enum TimerSource {
	'MOBILE' = 'MOBILE',
	'BROWSER' = 'BROWSER',
	'DESKTOP' = 'DESKTOP',
	'BROWSER_EXTENSION' = 'BROWSER_EXTENSION',
	'HUBSTAFF' = 'HUBSTAFF',
	'UPWORK' = 'UPWORK',
	'TEAMS' = 'TEAMS'
}

export enum TimeLogType {
	TRACKED = 'TRACKED',
	MANUAL = 'MANUAL',
	IDLE = 'IDLE',
	RESUMED = 'RESUMED'
}

export enum TimeLogSourceEnum {
	MOBILE = 'MOBILE',
	WEB_TIMER = 'BROWSER',
	DESKTOP = 'DESKTOP',
	BROWSER_EXTENSION = 'BROWSER_EXTENSION',
	HUBSTAFF = 'HUBSTAFF',
	UPWORK = 'UPWORK',
	TEAMS = 'TEAMS',
	CLOC = 'CLOC'
}
