export enum TimerSource {
	'MOBILE' = 'MOBILE',
	'BROWSER' = 'BROWSER',
	'DESKTOP' = 'DESKTOP',
	'BROWSER_EXTENSION' = 'BROWSER_EXTENSION',
	'HUBSTAFF' = 'HUBSTAFF',
	'UPWORK' = 'UPWORK',
	'TEAMS' = 'TEAMS'
}

export enum TimeLogType {
	TRACKED = 'TRACKED',
	MANUAL = 'MANUAL',
	IDLE = 'IDLE',
	RESUMED = 'RESUMED'
}

export enum TimeLogSourceEnum {
	MOBILE = 'MOBILE',
	WEB_TIMER = 'BROWSER',
	DESKTOP = 'DESKTOP',
	BROWSER_EXTENSION = 'BROWSER_EXTENSION',
	HUBSTAFF = 'HUBSTAFF',
	UPWORK = 'UPWORK',
	TEAMS = 'TEAMS',
	CLOC = 'CLOC'
}

export enum TimerStatusEnum {
	RUNNING = 'running',
	IDLE = 'idle',
	PAUSE = 'pause',
	ONLINE = 'online',
	SUSPENDED = 'suspended'
}

export enum ManualTimeReasons {
	LOST_ELECTRICITY = 'LOST_ELECTRICITY',
	LOST_INTERNET = 'LOST_INTERNET',
	FORGOT_TO_START_TIMER = 'FORGOT_TO_START_TIMER',
	ERROR = 'ERROR',
	UNPLANNED_WORK = 'UNPLANNED_WORK',
	TESTED_TIMER = 'TESTED_TIMER'
}
