export const EventLists = {
    webServerStarted: 'WEB_SERVER_STARTED',
    webServerStopped: 'WEB_SERVER_STOPPED',
    webServerStart: 'WEB_SERVER_START',
    webServerStop: 'WEB_SERVER_STOP',
    gotoSetting: 'GO_TO_SETTING',
    UPDATE_AVAILABLE: 'UPDATE_AVAILABLE',
    UPDATE_ERROR: 'UPDATE_ERROR',
    UPDATE_NOT_AVAILABLE: 'UPDATE_NOT_AVAILABLE',
    UPDATE_PROGRESS: 'UPDATE_PROGRESS',
    UPDATE_DOWNLOADED: 'UPDATE_DOWNLOADED',
    UPDATE_CANCELLED: 'UPDATE_CANCELLED'
  }
