import type { Metadata } from 'next';
import { connection } from 'next/server';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import ClientLayout from '@/components/layout/client-layout';
import { readRuntimeEnv } from '@/lib/runtime-env';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin']
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin']
});

export const metadata: Metadata = {
	title: 'Teams - NextJs Boilerplate',
	description: 'Generated by create next app'
};

export default async function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	// Per request, never prerendered: a page rendered at build time would freeze the build machine's env
	// into its HTML, which is exactly what a re-usable image must avoid.
	await connection();
	const apiUrl = readRuntimeEnv('NEXT_PUBLIC_TEAMS_API_URL') || process.env.NEXT_PUBLIC_TEAMS_API_URL;

	return (
		<html suppressHydrationWarning lang="en" dir="ltr">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<ClientLayout apiUrl={apiUrl}>
					<main id="main-content" role="main">
						{children}
					</main>
				</ClientLayout>
			</body>
		</html>
	);
}
