name: Server Web Build Apps

on:
  workflow_run:
    workflows: ["Release Apps"]
    branches: [apps]
    types:
      - completed

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release-linux:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [buildjet-8vcpu-ubuntu-2204]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: buildjet/setup-node@v4
        with:
          node-version: "20.19.0"
          cache: "yarn"

      - name: Change permissions
        run: "sudo chown -R $(whoami) ./*"

      - name: Install system dependencies
        run: "sudo apt-get update && sudo apt install -y curl gnupg git libappindicator3-1 ca-certificates binutils icnsutils graphicsmagick"

      - name: Fix node-gyp and Python
        run: python3 -m pip install packaging setuptools

      - name: Install latest version of NPM
        run: "sudo npm install -g npm@9"

      - name: Install latest node-gyp package
        run: "sudo npm install --quiet -g node-gyp@10.2.0"

      - name: Install Yarn dependencies
        run: "yarn install --network-timeout 1000000 --frozen-lockfile"

      - name: Bootstrap Yarn
        run: "yarn bootstrap"

      - name: Bump version
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.scripts/bump-version-electron.js')
            script.serverweb(true).then(console.log)
        env:
          PROJECT_REPO: "https://github.com/ever-co/ever-teams.git"
          DESKTOP_WEB_SERVER_APP_NAME: "ever-teams-web-server"
          COMPANY_SITE_LINK: "https://ever.team"
          DESKTOP_WEB_SERVER_APP_DESCRIPTION: "Ever Teams Web Server"
          DESKTOP_WEB_SERVER_APP_ID: "com.ever.everteamswebserver"

      - name: Build Web Server App
        run: "yarn build:web-server:linux:release:gh"
        env:
          USE_HARD_LINKS: false
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          EP_GH_IGNORE_TIME: true
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_TRACES_SAMPLE_RATE: "${{ secrets.SENTRY_TRACES_SAMPLE_RATE }}"
          SENTRY_HTTP_TRACING_ENABLED: "${{ secrets.SENTRY_HTTP_TRACING_ENABLED }}"
          SENTRY_POSTGRES_TRACKING_ENABLED: "${{ secrets.SENTRY_POSTGRES_TRACKING_ENABLED }}"
          SENTRY_PROFILING_ENABLED: "${{ secrets.SENTRY_PROFILING_ENABLED }}"
          DO_KEY_ID: ${{ secrets.DO_KEY_ID }}
          DO_SECRET_KEY: ${{ secrets.DO_SECRET_KEY }}
          NX_NO_CLOUD: true
          COMPANY_SITE: "Ever Teams"
          COMPANY_SITE_LINK: "https://ever.team"
          COMPANY_FACEBOOK_LINK: "https://www.facebook.com/everteamshq"
          COMPANY_TWITTER_LINK: "https://twitter.com/ever_teams"
          COMPANY_LINKEDIN_LINK: "https://www.linkedin.com/company/ever-co"
          PROJECT_REPO: "https://github.com/ever-co/ever-teams.git"
          DESKTOP_WEB_SERVER_APP_NAME: "ever-teams-web-server"
          DESKTOP_WEB_SERVER_APP_DESCRIPTION: "Ever Teams Web Server"
          DESKTOP_WEB_SERVER_APP_ID: "com.ever.everteamswebserver"
          DESKTOP_WEB_SERVER_APP_REPO_NAME: "ever-teams-web-server"
          DESKTOP_WEB_SERVER_APP_REPO_OWNER: "ever-co"
          DESKTOP_WEB_SERVER_APP_WELCOME_TITLE: "Welcome to Ever Teams"
          DESKTOP_WEB_SERVER_APP_WELCOME_CONTENT: "Ever Teams is a productivity tool that helps you to stay focused on your work and manage your team work better."
          I18N_FILES_URL: "https://raw.githubusercontent.com/ever-co/ever-teams/develop/apps/server-web/i18n"
          PLATFORM_LOGO: "https://ever.team/assets/ever-teams.png"
          GAUZY_DESKTOP_LOGO_512X512: "https://ever.team/assets/ever-teams-512x512.png"
          DESKTOP_WEB_SERVER_APP_DEFAULT_PORT: 3001
          GAUZY_API_SERVER_URL: "https://api.ever.team"
          NEXT_PUBLIC_GAUZY_API_SERVER_URL: "https://api.ever.team"

  release-mac:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: "20.19.0"
          cache: "yarn"

      - name: Fix node-gyp and Python
        run: python3 -m pip install --break-system-packages packaging setuptools

      - name: Install latest version of NPM
        run: "sudo npm install -g npm@9"

      - name: Install latest node-gyp package
        run: "sudo npm install --quiet -g node-gyp@10.2.0"

      - name: Install Yarn dependencies
        run: "yarn install --network-timeout 1000000 --frozen-lockfile"

      - name: Bootstrap Yarn
        run: "yarn bootstrap"

      - name: Bump version
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.scripts/bump-version-electron.js')
            script.serverweb(true).then(console.log)
        env:
          PROJECT_REPO: "https://github.com/ever-co/ever-teams.git"
          DESKTOP_WEB_SERVER_APP_NAME: "ever-teams-web-server"
          COMPANY_SITE_LINK: "https://ever.team"
          DESKTOP_WEB_SERVER_APP_DESCRIPTION: "Ever Teams Web Server"
          DESKTOP_WEB_SERVER_APP_ID: "com.ever.everteamswebserver"

      - name: Build Web Server App
        run: "yarn build:web-server:mac:release"
        env:
          USE_HARD_LINKS: false
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          EP_GH_IGNORE_TIME: true
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_TRACES_SAMPLE_RATE: "${{ secrets.SENTRY_TRACES_SAMPLE_RATE }}"
          SENTRY_HTTP_TRACING_ENABLED: "${{ secrets.SENTRY_HTTP_TRACING_ENABLED }}"
          SENTRY_POSTGRES_TRACKING_ENABLED: "${{ secrets.SENTRY_POSTGRES_TRACKING_ENABLED }}"
          SENTRY_PROFILING_ENABLED: "${{ secrets.SENTRY_PROFILING_ENABLED }}"
          DO_KEY_ID: ${{ secrets.DO_KEY_ID }}
          DO_SECRET_KEY: ${{ secrets.DO_SECRET_KEY }}
          NX_NO_CLOUD: true
          COMPANY_SITE: "Ever Teams"
          COMPANY_SITE_LINK: "https://ever.team"
          COMPANY_FACEBOOK_LINK: "https://www.facebook.com/everteamshq"
          COMPANY_TWITTER_LINK: "https://twitter.com/ever_teams"
          COMPANY_LINKEDIN_LINK: "https://www.linkedin.com/company/ever-co"
          PROJECT_REPO: "https://github.com/ever-co/ever-teams.git"
          DESKTOP_WEB_SERVER_APP_NAME: "ever-teams-web-server"
          DESKTOP_WEB_SERVER_APP_DESCRIPTION: "Ever Teams Web Server"
          DESKTOP_WEB_SERVER_APP_ID: "com.ever.everteamswebserver"
          DESKTOP_WEB_SERVER_APP_REPO_NAME: "ever-teams-web-server"
          DESKTOP_WEB_SERVER_APP_REPO_OWNER: "ever-co"
          DESKTOP_WEB_SERVER_APP_WELCOME_TITLE: "Welcome to Ever Teams"
          DESKTOP_WEB_SERVER_APP_WELCOME_CONTENT: "Ever Teams is a productivity tool that helps you to stay focused on your work and manage your team work better."
          I18N_FILES_URL: "https://raw.githubusercontent.com/ever-co/ever-teams/develop/apps/server-web/i18n"
          PLATFORM_LOGO: "https://ever.team/assets/ever-teams.png"
          GAUZY_DESKTOP_LOGO_512X512: "https://ever.team/assets/ever-teams-512x512.png"
          DESKTOP_WEB_SERVER_APP_DEFAULT_PORT: 3001
          GAUZY_API_SERVER_URL: "https://api.ever.team"
          NEXT_PUBLIC_GAUZY_API_SERVER_URL: "https://api.ever.team"

  release-windows:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: "20.19.0"
          cache: "yarn"

      - name: Fix node-gyp and Python
        run: python3 -m pip install packaging setuptools

      - name: Install latest version of NPM
        run: "npm install -g npm@9"

      - name: Install latest node-gyp package
        run: "npm install --quiet -g node-gyp@10.2.0"

      - name: Install Yarn dependencies
        run: "yarn install --network-timeout 1000000 --frozen-lockfile"

      - name: Bootstrap Yarn
        run: "yarn bootstrap"

      - name: Bump version
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.scripts/bump-version-electron.js')
            script.serverweb(true).then(console.log)
        env:
          PROJECT_REPO: "https://github.com/ever-co/ever-teams.git"
          DESKTOP_WEB_SERVER_APP_NAME: "ever-teams-web-server"
          COMPANY_SITE_LINK: "https://ever.team"
          DESKTOP_WEB_SERVER_APP_DESCRIPTION: "Ever Teams Web Server"
          DESKTOP_WEB_SERVER_APP_ID: "com.ever.everteamswebserver"

      - name: Print environment variable names
        run: |
          echo "Environment Variable Names:"
          printenv | cut -d= -f1

      - name: Build Web Server App
        run: "yarn build:web-server:windows:release:gh"
        env:
          USE_HARD_LINKS: false
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          EP_GH_IGNORE_TIME: true
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_TRACES_SAMPLE_RATE: "${{ secrets.SENTRY_TRACES_SAMPLE_RATE }}"
          SENTRY_HTTP_TRACING_ENABLED: "${{ secrets.SENTRY_HTTP_TRACING_ENABLED }}"
          SENTRY_POSTGRES_TRACKING_ENABLED: "${{ secrets.SENTRY_POSTGRES_TRACKING_ENABLED }}"
          SENTRY_PROFILING_ENABLED: "${{ secrets.SENTRY_PROFILING_ENABLED }}"
          DO_KEY_ID: ${{ secrets.DO_KEY_ID }}
          DO_SECRET_KEY: ${{ secrets.DO_SECRET_KEY }}
          NX_NO_CLOUD: true
          COMPANY_SITE: "Ever Teams"
          COMPANY_SITE_LINK: "https://ever.team"
          COMPANY_FACEBOOK_LINK: "https://www.facebook.com/everteamshq"
          COMPANY_TWITTER_LINK: "https://twitter.com/ever_teams"
          COMPANY_LINKEDIN_LINK: "https://www.linkedin.com/company/ever-co"
          PROJECT_REPO: "https://github.com/ever-co/ever-teams.git"
          DESKTOP_WEB_SERVER_APP_NAME: "ever-teams-web-server"
          DESKTOP_WEB_SERVER_APP_DESCRIPTION: "Ever Teams Web Server"
          DESKTOP_WEB_SERVER_APP_ID: "com.ever.everteamswebserver"
          DESKTOP_WEB_SERVER_APP_REPO_NAME: "ever-teams-web-server"
          DESKTOP_WEB_SERVER_APP_REPO_OWNER: "ever-co"
          DESKTOP_WEB_SERVER_APP_WELCOME_TITLE: "Welcome to Ever Teams"
          DESKTOP_WEB_SERVER_APP_WELCOME_CONTENT: "Ever Teams is a productivity tool that helps you to stay focused on your work and manage your team work better."
          I18N_FILES_URL: "https://raw.githubusercontent.com/ever-co/ever-teams/develop/apps/server-web/i18n"
          PLATFORM_LOGO: "https://ever.team/assets/ever-teams.png"
          GAUZY_DESKTOP_LOGO_512X512: "https://ever.team/assets/ever-teams-512x512.png"
          DESKTOP_WEB_SERVER_APP_DEFAULT_PORT: 3001
          GAUZY_API_SERVER_URL: "https://api.ever.team"
          NEXT_PUBLIC_GAUZY_API_SERVER_URL: "https://api.ever.team"
